-- 1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as Total_revenue
FROM customer
GROUP BY gender;

-- 2. Which customers used a discount but still spent more than the average purchase amount?
SELECT *
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >(
	SELECT avg(purchase_amount)
	from customer
);

-- 3. Which are the top five products with the highest average review rating?
SELECT item_purchased,ROUND(AVG(review_rating::numeric),2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- 4. Compare the average purchase amounts between standard and express shipping?
SELECT shipping_type,ROUND(AVG(purchase_amount),2)as avg_purchase_amount
FROM customer
WHERE shipping_type IN('Standard','Express')
GROUP BY shipping_type

-- 5. Do subscribed customers spend more ? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,ROUND(AVG(purchase_amount),2) AS average_spend,
SUM(purchase_amount) AS Total_Revenue,
COUNT(customer_id) as total_customer
FROM customer
GROUP BY subscription_status
ORDER BY Total_Revenue,average_spend DESC

-- 6. Which 5 produts have the highest percentage of purchases with the discounts applied?
SELECT * FROM customer;
SELECT 
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- 7. Segment customers into New, Returning, and Loyal based on their total number of previous purchase and show the count of each segment. 
WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment

-- 8. What are the top 3 most purchased products within each category?
WITH item_counts AS(
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM CUSTOMER 
GROUP BY category, item_purchased
)
SELECT item_rank, category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <=3

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

-- 10. What is the revenue contribution of each age group?
SELECT age_group,SUM(purchase_amount) AS total_revenue, 
	ROUND(AVG(purchase_amount),2) AS average_purchase,
	COUNT(*) AS purchase_count
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


-- Does applying a discount actually increase the average purchase amount?
SELECT discount_applied,COUNT(*) AS purchase_amount, SUM(purchase_amount) AS total_revenue, AVG(purchase_amount) AS average_purchase
FROM customer
GROUP BY discount_applied

-- Which product categories generate the most revenue, and how does their average purchase amount compare?
SELECT category,COUNT(*) AS purchase_count,SUM(purchase_amount)AS total_revenue,ROUND(AVG(purchase_amount),2) Avg_purchase_amount
FROM customer
GROUP BY category

